development:
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

production:
  secret_key_base: d49afa9b01764333755017e993c3d64768e93911cbf2f8468b727a781f8fff82baf575231527f9a27dd504a805b9680d0764b0daec55bfc778354f8eb35e4525
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
